<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>distmq</AssemblyName>
    <RootNamespace>DistMq.Cli</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.CommandLine" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\DistMq.Client\DistMq.Client.csproj" />
  </ItemGroup>
</Project>
